server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-management-service
          uri: lb://user-management-service
          predicates:
            - Path=/api/users/**
        - id: vehicle-management-service
          uri: lb://vehicle-management-service
          predicates:
            - Path=/api/vehicles/**
        - id: trip-management-service
          uri: lb://trip-management-service
          predicates:
            - Path=/api/trips/**
        - id: maintenance-service
          uri: lb://maintenance-service
          predicates:
            - Path=/api/maintenance/**
        - id: financial-service
          uri: lb://financial-service
          predicates:
            - Path=/api/financials/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
